{{- if and .Values.postgres.persistence.enabled (not .Values.postgres.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mealie.fullname" . }}-postgres-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}

  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
{{- end }}
