apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mealie.fullname" . }}-postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.database.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.database.name | quote }}
