apiVersion: v1
kind: Service
metadata:
  name: {{ include "mealie.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mealie.fullname" . }}-app
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.mealie.service.type }}
  selector:
    app: mealie
  ports:
    - protocol: TCP
      port: {{ .Values.mealie.service.port }}
      targetPort: {{ .Values.mealie.service.targetPort }}
